# Site settings
title: OTM Development Standards
email: mike@oldtownmediainc.com
description: > # this means to ignore newlines until "baseurl:"
  Old Town Media development standards
#baseurl: "/otm-development-standards" # the subpath of your site, e.g. /blog/
baseulr: "/"
url: "http://www.oldtownmediainc.com" # the base hostname & protocol for your site
twitter_username: oldtownmedia
github_username:  oldtownmedia

# Build settings
markdown: Redcarpet
